#!/bin/bash

command="$1"
if [ -z $command ]; then
  echo "Usage: $0 <command>"
  echo "  ex: $0 bash  # will run 'bash' with Docker"
  exit
fi

docker run --rm -v "$PWD:/app" -it logging_eap "$command"
