## Ruby Agent Logging Early Access Performance Test Plan
#

## Before updating your `newrelic.yml`, make sure your Gemfile is using
## the EAP test branch:
## 1. Replace your installation of `newrelic_rpm` with the following:
## gem 'newrelic_rpm', git: 'https://www.github.com/newrelic/newrelic-ruby-agent.git', branch: 'logging-initiative'
## 2. Run `bundle update newrelic_rpm`

## The following are a list of configs specific to the logging initiative EAP.
## Uncomment a group when it's time to move to that phase of the EAP.
## Comment out the group that is no longer active.

## Phase 0: All settings off by default (3 days)
# application_logging:
#   enabled: false

## TESTING LOG FORWARDING ##
## Phase 1: Limited log lines forwarded to NR1 (3 days)
# application_logging:
#   enabled: true
#   forwarding:
#     enabled: true

## Phase 2: Maximum log lines forwarded to NR1 (3 days)
# application_logging:
#   enabled: true
#   forwarding:
#     enabled: true
#     max_samples_stored: 100000

## Phase 3: Minimum log lines forwarded to NR1 (3 days)
# application_logging:
#   enabled: true
#   forwarding:
#     enabled: true
#     max_samples_stored: 1000

## TESTING LOCAL LOG DECORATION ##
## Phase 4: Enable local log decoration (3 days)
# application_logging:
#   enabled: true
#   local_decorating:
#     enabled: true
